---

- name: Make sure git-core is installed.
  apt: pkg=git-core state=installed

- name: Install gitreceive.
  get_url: url=https://raw.github.com/progrium/gitreceive/master/gitreceive dest=/usr/bin/gitreceive mode=0755

- name: Check if path exists
  stat: path=/home/git
  register: check_path

- name: Init gitreceive.
  command: /usr/bin/gitreceive init
  when: (check_path.stat.exists == false)


- name: Add git to sudoers.d.
  action: template src=../templates/git dest=/etc/sudoers.d/80-git validate='visudo -cf %s'

- name: Make sure permissions are correct.
  file: path=/etc/sudoers.d/80-git owner=root group=root mode=0440

- name: Remove standard receiver.
  command: rm /home/git/receiver

- name: Add octohost receiver.
  get_url: url=https://raw.github.com/octohost/octohost/master/receiver.sh dest=/home/git/receiver mode=0755
  
- name: Add /home/git/src/
  command: mkdir -p /home/git/src/; chown git.git /home/git/src/; chmod 775 /home/git/src/